### PR TITLE
Add Simple and Common Feature Detector/Describers

### PR DESCRIPTION
**Pull request by LBern**
## General
This PR introduces common detectors such as `freak` and `brief` for quick and easy testing. 

Example of a SURF detector with a FREAK descriptor:
Screenshot from 2021-10-07 17-15-46

## Changelog
 * Added `feature_extraction.py` that detects and describes keypoints in a given image
 * Moved the external detection from `ros_interface.py` to the `feature_extraction.py`
 * Added launch file and config for the LK tracker

### CODE REVIEW

**Comment by LBern** [comment]
@smauq Just for reference. I'm working on this now

**Comment by LBern** [comment]
@smauq Here again, the initial version is done. It should work fine with the standard cv extractors. However, I couldn't test the r2d2 interface as this one is not working on my machine right now. Need to investigate this separately.

**Review by smauq — APPROVED** [review]
Looks good to me, very nice! I tested and it works well with the r2d2 features, no problems there. But I think from the previous PR we have one issue maybe due to the change in the CMake file. Even after sourcing, I don't have the launch or python files added to the things that rosrun/roslaunch suggests (the entire package maplab_features doens't have anything or exist). Does it work for you on a clean build?

**Comment by LBern** [comment]
> Looks good to me, very nice! I tested and it works well with the r2d2 features, no problems there. But I think from the previous PR we have one issue maybe due to the change in the CMake file. Even after sourcing, I don't have the launch or python files added to the things that rosrun/roslaunch suggests (the entire package maplab_features doens't have anything or exist). Does it work for you on a clean build?

Great! I'll merge this one and in a separate will look into the building issues.

**Pull request merged**
